---
- name: Installs and starts Curr-Rates Service
  hosts: ubuntu # Tested on Ubuntu 22.04 LTS
  become: true
  gather_facts: false

  tasks:
    - name: Install necessary packages
      ansible.builtin.package:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Enable docker service 
      ansible.builtin.service:
        name: docker.service
        enabled: yes
        state: started

    - name: Copy App folder
      ansible.builtin.copy:
        src: app/
        dest: /tmp/curr-rates/
        owner: ansible
        group: ansible
        mode: preserve

    - name: Start docker compose
      ansible.builtin.command: 
        argv: ["docker-compose", "up", "--detach", "--build"] 
        chdir: /tmp/curr-rates/   
